//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_Documental.Models.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Documento = new HashSet<Documento>();
            this.Usuario3 = new HashSet<Usuario>();
        }
    
        public int IdArea { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioEdicion { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
        public Nullable<int> IdUsuarioEliminacion { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
        public string Clave { get; set; }
    
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ICollection<Usuario> Usuario3 { get; set; }
    }
}
