//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_Documental.Models.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Area1 = new HashSet<Area>();
            this.Area2 = new HashSet<Area>();
            this.Area3 = new HashSet<Area>();
            this.Configuracion = new HashSet<Configuracion>();
            this.Configuracion1 = new HashSet<Configuracion>();
            this.Departamento1 = new HashSet<Departamento>();
            this.Departamento2 = new HashSet<Departamento>();
            this.Departamento3 = new HashSet<Departamento>();
            this.Documento = new HashSet<Documento>();
            this.Documento1 = new HashSet<Documento>();
            this.Documento2 = new HashSet<Documento>();
        }
    
        public int IdUsuario { get; set; }
        public string Alias { get; set; }
        public string Nombre { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdUsuarioEdicion { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
        public Nullable<int> IdUsuarioEliminacion { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
        public string Salt { get; set; }
        public Nullable<int> IdGrupoLector { get; set; }
    
        public virtual ICollection<Area> Area1 { get; set; }
        public virtual ICollection<Area> Area2 { get; set; }
        public virtual ICollection<Area> Area3 { get; set; }
        public virtual ICollection<Configuracion> Configuracion { get; set; }
        public virtual ICollection<Configuracion> Configuracion1 { get; set; }
        public virtual ICollection<Departamento> Departamento1 { get; set; }
        public virtual ICollection<Departamento> Departamento2 { get; set; }
        public virtual ICollection<Departamento> Departamento3 { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual ICollection<Documento> Documento1 { get; set; }
        public virtual ICollection<Documento> Documento2 { get; set; }
        public virtual Area Area { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual GrupoLector GrupoLector { get; set; }
    }
}
